# Generated by Django 5.2.11 on 2026-07-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_remove_emailtemplate_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_body',
            field=models.TextField(help_text='Pre-compiled MJML (HTML) with Jinja2 variables: {{ company_name }}, {{ email }}, {{ definite_article_company_name }}'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject_template',
            field=models.CharField(help_text="Jinja2 template for subject. Variables: {{ company_name }}, {{ email }}, {{ definite_article_company_name }} (name with French article, e.g. 'la MSP du Marais')", max_length=500),
        ),
    ]
