# Generated by Django 5.2.11 on 2026-09-03 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_emailtemplate_html_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_body',
            field=models.TextField(help_text='Pre-compiled MJML (HTML) with Jinja2 variables: {{ company_name }}, {{ email }}, {{ definite_article_company_name }}, {{ unsubscribe_url }}. Every template MUST include an unsubscribe link, e.g. <a href="{{ unsubscribe_url }}">Se désabonner</a> — if it is missing, a plain footer is appended automatically at send time.'),
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('twenty_crm_id', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('link', 'Unsubscribe link'), ('list_header', 'List-Unsubscribe one-click'), ('manual', 'Manual (admin)')], default='link', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('sent_email', models.ForeignKey(blank=True, help_text='The email whose link triggered this unsubscribe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unsubscribes', to='emails.sentemail')),
            ],
            options={
                'ordering': ['-unsubscribed_at'],
            },
        ),
    ]
