# Generated by Django 5.2.11 on 2026-07-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebProspectRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('scraper', models.CharField(default='apmsl', help_text="Scraper used, e.g. 'apmsl'", max_length=50)),
                ('ask_confirmation', models.BooleanField(default=True)),
                ('total', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('already_present_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebProspectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('created', 'Created'), ('already_present', 'Already present'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('twenty_company_id', models.CharField(blank=True, default='', max_length=255)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Parsed source data for this record (for audit / re-parse)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='webprospects.webprospectrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
