# Generated by Django 5.2.11 on 2026-07-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webprospectrun',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webprospectrecord',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('already_present', 'Already present'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20),
        ),
    ]
