# Generated by Django 5.2.11 on 2026-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprospects', '0002_webprospectrun_updated_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webprospectrecord',
            name='duplicate_company_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='webprospectrecord',
            name='duplicate_company_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
