# Generated by Django 5.2.11 on 2026-07-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprospects', '0003_webprospectrecord_duplicate_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadNounGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_noun', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('f', 'Feminine (la)'), ('m', 'Masculine (le)'), ('unknown', 'Unknown (needs review)')], default='unknown', max_length=10)),
                ('note', models.CharField(blank=True, default='', help_text="Optional: expansion or reason (e.g. 'CPTS = communauté → f')", max_length=255)),
            ],
            options={
                'ordering': ['head_noun'],
            },
        ),
    ]
