# Generated by Django 5.2.11 on 2026-06-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name, e.g. 'CPTS CSV 2024'", max_length=255, unique=True)),
                ('csv_name_column', models.CharField(help_text='CSV column for company name', max_length=255)),
                ('csv_email_column', models.CharField(help_text='CSV column for email', max_length=255)),
                ('csv_postcode_column', models.CharField(help_text='CSV column for postal code (first 2 chars used)', max_length=255)),
                ('csv_domain_column', models.CharField(blank=True, default='', help_text='CSV column for domain (optional)', max_length=255)),
                ('csv_delimiter', models.CharField(default=';', help_text='CSV field delimiter', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='emails.companytype')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rows', models.IntegerField(default=0)),
                ('deduplicated_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.companytype')),
                ('transformer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to='twenty.transformer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
